-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 14:23:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FileSTransfer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FileSTransfer` ;

-- -----------------------------------------------------
-- Schema FileSTransfer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FileSTransfer` DEFAULT CHARACTER SET utf8 ;
USE `FileSTransfer` ;

-- -----------------------------------------------------
-- Table `FileSTransfer`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FileSTransfer`.`user` ;

CREATE TABLE IF NOT EXISTS `FileSTransfer`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(93) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FileSTransfer`.`relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FileSTransfer`.`relationship` ;

CREATE TABLE IF NOT EXISTS `FileSTransfer`.`relationship` (
  `user` INT NOT NULL,
  `friend` INT NOT NULL,
  `flag` TINYINT(1) NOT NULL,
  `rtime` TIMESTAMP(6) NULL DEFAULT '2018-10-25 14:17:00.000000',
  PRIMARY KEY (`friend`, `user`),
  INDEX `fk_user_has_user_user1_idx` (`friend` ASC),
  INDEX `fk_user_has_user_user_idx` (`user` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`user`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`friend`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FileSTransfer`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FileSTransfer`.`files` ;
SET session
sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
CREATE TABLE IF NOT EXISTS `FileSTransfer`.`files` (
  `fileid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(100) NOT NULL,
  `filepath` VARCHAR(150) NOT NULL,
  `uploadtime` TIMESTAMP(6) NULL DEFAULT '2018-10-25 14:17:00.000000',
  `user_userid` INT NOT NULL,
  `quote` INT NULL,
  PRIMARY KEY (`fileid`),
  INDEX `fk_files_user1_idx` (`user_userid` ASC),
  CONSTRAINT `fk_files_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FileSTransfer`.`filerecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FileSTransfer`.`filerecord` ;

CREATE TABLE IF NOT EXISTS `FileSTransfer`.`filerecord` (
  `user_userid` INT NOT NULL,
  `files_fileid` INT UNSIGNED NOT NULL,
  `flag` TINYINT NOT NULL,
  `recordtime` TIMESTAMP(6) NULL DEFAULT '2018-10-25 14:17:00.000000',
  PRIMARY KEY (`user_userid`, `files_fileid`),
  INDEX `fk_user_has_files_files1_idx` (`files_fileid` ASC),
  INDEX `fk_user_has_files_user1_idx` (`user_userid` ASC),
  CONSTRAINT `fk_user_has_files_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_files_files1`
    FOREIGN KEY (`files_fileid`)
    REFERENCES `FileSTransfer`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FileSTransfer`.`sendrecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FileSTransfer`.`sendrecord` ;

CREATE TABLE IF NOT EXISTS `FileSTransfer`.`sendrecord` (
  `user_userid` INT NOT NULL,
  `user_userid1` INT NOT NULL,
  `files_fileid` INT UNSIGNED NOT NULL,
  `sendtime` TIMESTAMP(6) NULL DEFAULT '2018-10-25 14:17:00.000000',
`note` TEXT NULL,
  INDEX `fk_sendrecord_user1_idx` (`user_userid` ASC),
  INDEX `fk_sendrecord_user2_idx` (`user_userid1` ASC),
  INDEX `fk_sendrecord_files1_idx` (`files_fileid` ASC),
  CONSTRAINT `fk_sendrecord_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sendrecord_user2`
    FOREIGN KEY (`user_userid1`)
    REFERENCES `FileSTransfer`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sendrecord_files1`
    FOREIGN KEY (`files_fileid`)
    REFERENCES `FileSTransfer`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;